### PR TITLE
Enable static lookup for zip codes in MA.

### PR DESCRIPTION
**Pull request by hblumberg**
Per @mzagaja's suggestion, this PR enables us to look up the latitude and longitude of zip codes without hitting the Geocoder API (which is getting expensive).

To get these latitudes and longitudes, I created a Google Sheet with all MA zip codes, created a custom formula (`GEOCODE, below`), and then converted the results to JSON.
```
function GEOCODE(zipCode) {
  var response = Maps.newGeocoder().geocode(zipCode);
  var location = response.results[0].geometry.location;
  return `${location.lat}, ${location.lng}`;
}
```

### Test Plan:
* Add temporary logging or a breakpoint to `return zipCodes[req.body.zipCode];` in `distance-utils`.
* Search for a zip code in MA. See logging / breakpoint hit. Ensure results match those on the live site.
* Search for a zip code outside MA. See that results are still returned as expected.

### CODE REVIEW

**Comment by mwellman17** [comment]
This PR directly conflicts with PR#92 Allow search by city/town. I would vote for us combining the two: if the backend receives a string containing 5 digits, it proceeds with static lookup. Otherwise it proceeds with geocoder to allow a more broad range of searches. Thoughts?

**Comment by hblumberg** [comment]
Yes, perfect! I'll rebase on your branch now for simplicity.

**Comment by johndeyrup** [comment]
I would probably go for a cache with a really long ttl

**Comment by hblumberg** [comment]
@johndeyrup Thoughts on this being a cost-saving measure until someone can investigate caching?

**Comment by snyderc** [comment]
If we're caching zip code latitude/longitude, can we also cache the city/town latitude/longitude? Matt's goal is to eliminate the geocoder because of cost issues, and if we allow city/town lookup, we're not going to achieve the cost savings from this PR.

**Comment by hblumberg** [comment]
> If we're caching zip code latitude/longitude, can we also cache the city/town latitude/longitude? Matt's goal is to eliminate the geocoder because of cost issues, and if we allow city/town lookup, we're not going to achieve the cost savings from this PR.

Yup! I can add cities and towns too. But I think it'll get us non-zero cost savings since folks may still enter zip codes. Maybe not enough to make it worth it so happy to abandon if y'all prefer!

**Comment by hblumberg** [comment]
Updates from last night's conversation! Since Google Geocoder is so expensive, @mzagaja suggested we move to Pelias:

> We have an open unlimited Pelias server that is setup for MA at http://pelias.mapc.org

We chose not to because entering only a zip code wasn't working well. (See [Slack conversation](https://vaccinatemaworkspace.slack.com/archives/C01MQMVQB71/p1613945622053700?thread_ts=1613943352.046900&cid=C01MQMVQB71).)

This static lookup + Pelias might be a good way to avoid using Google Geocoder for all searches!

**Comment by mzagaja** [comment]
I like using static lookup for zip codes and then falling back to Pelias for non-zip searches.

**Review by johndeyrup — APPROVED** [review]

**Pull request merged**
