### PR TITLE
Change yellow star to dark blue for better accessibility

### PR DESCRIPTION
**Pull request by madeleine-b**
We got some user feedback that the yellow stars are hard to see against the map. I changed the star to a dark blue.

**Old**
Screen Shot 2021-02-09 at 12 43 22 AM

**New**
Screen Shot 2021-02-09 at 12 43 07 AM

### CODE REVIEW

**Comment by johndeyrup** [comment]
I feel like the blue is hard to see too; picking colors is hard though. We could try different symbols?

**Comment by madeleine-b** [comment]
I can make it an even darker blue? Making symbols alone the difference will be hard for the dense overlapping area near Boston.

**Comment by johndeyrup** [comment]
The blue star that overlaps Worcester is hard to see; the other ones seem fine.

**Comment by madeleine-b** [comment]
It seems like an unpleasant bright blue stands out against text (see Northampton instead of Worcester now) better than dark

Screen Shot 2021-02-09 at 2 30 42 PM

Screen Shot 2021-02-09 at 2 29 25 PM

**Comment by johndeyrup** [comment]
yeah looks clearer; I am sure a designer would know the right colors to pick here, but looks good to me.

**Pull request merged**
