### PR TITLE
Add Google Analytics to React site

### PR DESCRIPTION
**Pull request by snyderc**
Google Analytics in React/Next.js

Test Plan:
- Navigate to each page on localhost in the dev site 5 times. For some pages (e.g. eligibility), only use the navbar link, instead of directly accessing the URL in the browser. Look at the realtime GA analytics and make sure the pages are coming up and with the number of hits expected.

Implementation Notes:

I ended up using https://stackoverflow.com/a/62552263 which assumes that we are using the standard Next.js router (we should be!).

There are abstraction libraries like react-ga, but for Next.js there are a couple options:

next-ga -- older method, the package maintainer recommends looking at the newer experimental method and copying the code manually into your project

https://github.com/vercel/next.js/tree/canary/packages/next-plugin-google-analytics -- newer method, but still experimental

The tutorials you see online are basically manual implementations of one or the other of the above methods.

### CODE REVIEW

**Comment by snyderc** [comment]
Tested and seeing the dev pages display in the realtime Google Analytics!

**Review by hblumberg — APPROVED** [review]
This is awesome!! To confirm: on the live site, we only have page view data, correct? (We're not tracking any button clicks, etc.?)

Also, we might want to rename this component `seoAndAnalytics` or something? Doesn't need to be now (:

**Comment by snyderc** [comment]
> This is awesome!! To confirm: on the live site, we only have page view data, correct? (We're not tracking any button clicks, etc.?)
> 
> Also, we might want to rename this component `seoAndAnalytics` or something? Doesn't need to be now (:

Yeah, there's a handful of generic events (page_view, session_start, click) but nothing specific, and the ejs site doesn't seem to have any tracking on specific buttons/etc.

Agree renaming is in order -- maybe `PageHead` or something that indicates that this component injects into the `<head>` tag of the HTML

**Comment by hblumberg** [comment]
> Agree renaming is in order -- maybe PageHead or something that indicates that this component injects into the <head> tag of the HTML

Ooh yes, that's perfect!

**Comment by snyderc** [comment]
Merged in https://github.com/codeforboston/vaccinatema/pull/78

**Pull request closed without merging**
