### PR TITLE
Zzany/temp airtable backend

### PR DESCRIPTION
**Pull request by zzany**
Currently what's running... I realize not ideal, just an FYI

### CODE REVIEW

**Comment by madeleine-b** [comment]
@mzagaja PTAL although note this PR includes API keys and other sensitive info

**Comment by madeleine-b** [comment]
@zzany is this ready for review?

**Comment by mzagaja** [comment]
I recommend we merge this in with the understanding that it's just sharing the current state of things, and then create issues to improve it and/or turn into a Lambda function so we don't have to run it locally.

**Comment by johndeyrup** [comment]
yeah this fine to merge.

**Comment by mzagaja** [comment]
I'm actually just going to close this. After discussion last night we agreed scrapers are going into separate AWS Lambda functions.

**Pull request closed without merging**
