### PR TITLE
Add a GitHub action to run eslint on PR.

### PR DESCRIPTION
**Pull request by hblumberg**
This PR introduces a GitHub action that runs when PRs are created or updated. This will ensure all of our files stay `eslint`ed!

### Test Plan:
* Make a commit with a lint error; see failure! https://github.com/codeforboston/vaccinatema/pull/59/checks?check_run_id=1914941911

### CODE REVIEW

**Comment by johndeyrup** [comment]
will the linter create a new pr as part of the action?

**Comment by hblumberg** [comment]
> will the linter create a new pr as part of the action?

I wasn't planning to add a commit with fixes, but I think we could! I don't know what people prefer.

**Comment by mzagaja** [comment]
Ship it!

**Review by johndeyrup — APPROVED** [review]
love it!

**Pull request merged**
