### PR TITLE
update to acknowledgement - no real opinion on final version

### PR DESCRIPTION
**Pull request by zzany**
Just wanted to open discussion
image

### CODE REVIEW

**Review by mzagaja — APPROVED** [review]

**Comment by mzagaja** [comment]
This seems good to me for now. Wondering if you want to put the Code for Boston logo as well?

**Comment by zzany** [comment]
Can you send me a vector image version? Don't want to scale down and create a pixelated / bad version

**Comment by johndeyrup** [comment]
:+1:

**Comment by mzagaja** [comment]
I only have PNG versions, if you want SVG ping @WheresHJ on Slack, I think he has them.

**Pull request merged**
