### PR TITLE
Update Phase & image

### PR DESCRIPTION
**Pull request by JesseWeinstein**
And clarify phrasing

### CODE REVIEW

**Comment by madeleine-b** [comment]
@johndeyrup

**Comment by johndeyrup** [comment]
LGTM; usually a good idea to show a screen shot of the working changes.

**Comment by JesseWeinstein** [comment]
I can't make a screenshot because when I try to spin up the repo, it dies complaining about not having an Airtable API key. :-) Probably worth adjusting that.

**Comment by JesseWeinstein** [comment]
I have now fixed that (but not committed the change), so here is a screen shot: 
image

**Pull request merged**
