### PR TITLE
Remove leftovers from preview time

### PR DESCRIPTION
**Pull request by JesseWeinstein**
I *think* these are unused...

### CODE REVIEW

**Comment by johndeyrup** [comment]
Can you show screenshots of the pages

**Review by mzagaja — APPROVED** [review]
Good use of remove dead code!

**Comment by JesseWeinstein** [comment]
@johndeyrup -- sure, but there will be no visible changes, because all the code I removed was already set to "display: none" or aria-hidden="true". Are you sure you want screenshots?
@mzagaja I actually did it manually -- which dead code removal tool were you referring to?

(edit: mention aria-hidden="true")

**Comment by johndeyrup** [comment]
The screenshots are more to show that everything still runs fine

**Comment by mzagaja** [comment]
@JesseWeinstein I was referring to the refactoring technique of removing dead or unused code. You can read more about that, and other refactoring at https://refactoring.guru/smells/dead-code.

**Comment by JesseWeinstein** [comment]
Ah, that makes sense. Yes, I love refactoring (and am always looking for tools to make doing so safer).

**Comment by JesseWeinstein** [comment]
Screenshots to confirm things are still working:
image

image

**Pull request merged**
